name: flutter_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/imagen.png
    - assets/images/background.jpg
    - assets/images/lugares.jpg
    - assets/images/aprender.jpg
    - assets/images/evaluacion.png
    - assets/images/avisos.jpg